export enum ChoreStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
}

export enum SubtaskStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
}

export enum ChoreSwapRequestStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum ChoreAction {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  COMPLETED = "COMPLETED",
  ASSIGNED = "ASSIGNED",
  DELETED = "DELETED",
  SWAPPED = "SWAPPED",
  TEMPLATE_CREATED = "TEMPLATE_CREATED",
  TEMPLATE_UPDATED = "TEMPLATE_UPDATED",
  TEMPLATE_DELETED = "TEMPLATE_DELETED",
  RECURRENCE_CHANGED = "RECURRENCE_CHANGED",
}
