export enum PollType {
  SINGLE_CHOICE = "SINGLE_CHOICE",
  MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
  RANKED_CHOICE = "RANKED_CHOICE",
  EVENT_DATE = "EVENT_DATE",
}

export enum PollStatus {
  OPEN = "OPEN",
  CLOSED = "CLOSED",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
}
