export enum NotificationType {
  NEW_MESSAGE = "NEW_MESSAGE",
  CHORE_ASSIGNED = "CHORE_ASSIGNED",
  EXPENSE_UPDATED = "EXPENSE_UPDATED",
  PAYMENT_REMINDER = "PAYMENT_REMINDER",
  EVENT_REMINDER = "EVENT_REMINDER",
  OTHER = "OTHER",
}
